name: 部署到GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置Node.js环境
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmmirror.com'
          cache: 'yarn'

      - name: 安装依赖
        run: yarn --frozen-lockfile

      - name: 构建项目
        run: yarn build:h5
        
      - name: 部署到GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/build/h5
          branch: gh-pages
          clean: true